version: "2.1"

services:
  redis:
    image: redis:5.0.10
    depends_on:
      - statsd-exporter
    command: redis-server --requirepass ${REDIS_PASSWORD}

  postgres:
    image: postgres:9.6
    extends:
      file: airflow-env.yml
      service: airflow_env
    depends_on:
      - statsd-exporter
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata

  webserver:
    image: airflow-docker:latest
    build: .
    restart: always
    extends:
      file: airflow-env.yml
      service: airflow_env
    depends_on:
      - postgres
      - redis
      - statsd-exporter
    environment:
      - LOAD_EXAMPLES=n
      - EXECUTOR=Celery
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  flower:
    image: airflow-docker:latest
    build: .
    restart: always
    extends:
      file: airflow-env.yml
      service: airflow_env
    depends_on:
      - redis
    environment:
      - EXECUTOR=Celery
    ports:
      - "5555:5555"
    command: flower

  scheduler:
    image: airflow-docker:latest
    build: .
    restart: always
    extends:
      file: airflow-env.yml
      service: airflow_env
    depends_on:
      - webserver
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
    environment:
      - LOAD_EXAMPLES=n
      - EXECUTOR=Celery
    command: scheduler

  worker:
    image: airflow-docker:latest
    build: .
    restart: always
    extends:
      file: airflow-env.yml
      service: airflow_env
    depends_on:
      - scheduler
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
    environment:
      - EXECUTOR=Celery
    command: worker

  statsd-exporter:
    image: prom/statsd-exporter:latest
    container_name: airflow-statsd-exporter
    command: "--statsd.listen-udp=:8125 --web.listen-address=:9102"
    ports:
      - 9123:9102
      - 8125:8125/udp
